version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file template.yaml 
                                   --s3-bucket pg23appdeploybucket
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml